package tfisher.entities;
// Generated 13 ??? 2014 8:05:22 ?? by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 * User generated by hbm2java
 */
@Component
public class User  implements java.io.Serializable {


     private String idStr;
     private String name;
     private String screenName;
     private Integer followersCount;
     private Integer friendsCount;
     private String createdAt;
     private Integer NUtcOffset;
     private Integer statusesCount;
     private String lang;
     private String NTimeZone;
     private Set tweets = new HashSet(0);

    public User() {
    }

	
    public User(String idStr) {
        this.idStr = idStr;
    }
    public User(String idStr, String name, String screenName, Integer followersCount, Integer friendsCount, String createdAt, Integer NUtcOffset, Integer statusesCount, String lang, String NTimeZone, Set tweets) {
       this.idStr = idStr;
       this.name = name;
       this.screenName = screenName;
       this.followersCount = followersCount;
       this.friendsCount = friendsCount;
       this.createdAt = createdAt;
       this.NUtcOffset = NUtcOffset;
       this.statusesCount = statusesCount;
       this.lang = lang;
       this.NTimeZone = NTimeZone;
       this.tweets = tweets;
    }
   
    public String getIdStr() {
        return this.idStr;
    }
    
    public void setIdStr(String idStr) {
        this.idStr = idStr;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getScreenName() {
        return this.screenName;
    }
    
    public void setScreenName(String screenName) {
        this.screenName = screenName;
    }
    public Integer getFollowersCount() {
        return this.followersCount;
    }
    
    public void setFollowersCount(Integer followersCount) {
        this.followersCount = followersCount;
    }
    public Integer getFriendsCount() {
        return this.friendsCount;
    }
    
    public void setFriendsCount(Integer friendsCount) {
        this.friendsCount = friendsCount;
    }
    public String getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }
    public Integer getNUtcOffset() {
        return this.NUtcOffset;
    }
    
    public void setNUtcOffset(Integer NUtcOffset) {
        this.NUtcOffset = NUtcOffset;
    }
    public Integer getStatusesCount() {
        return this.statusesCount;
    }
    
    public void setStatusesCount(Integer statusesCount) {
        this.statusesCount = statusesCount;
    }
    public String getLang() {
        return this.lang;
    }
    
    public void setLang(String lang) {
        this.lang = lang;
    }
    public String getNTimeZone() {
        return this.NTimeZone;
    }
    
    public void setNTimeZone(String NTimeZone) {
        this.NTimeZone = NTimeZone;
    }
    public Set getTweets() {
        return this.tweets;
    }
    
    public void setTweets(Set tweets) {
        this.tweets = tweets;
    }




}


