package tdao.entities;
// Generated Jun 4, 2014 12:06:28 PM by Hibernate Tools 3.6.0



/**
 * Hashtags generated by hbm2java
 */
public class Hashtags  implements java.io.Serializable {


     private long id;
     private Tweet tweet;
     private String indices;
     private String text;

    public Hashtags() {
    }

	
    public Hashtags(long id) {
        this.id = id;
    }
    public Hashtags(long id, Tweet tweet, String indices, String text) {
       this.id = id;
       this.tweet = tweet;
       this.indices = indices;
       this.text = text;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Tweet getTweet() {
        return this.tweet;
    }
    
    public void setTweet(Tweet tweet) {
        this.tweet = tweet;
    }
    public String getIndices() {
        return this.indices;
    }
    
    public void setIndices(String indices) {
        this.indices = indices;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }




}


