package tfisher.entities;
// Generated Jun 4, 2014 12:06:28 PM by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Places generated by hbm2java
 */
public class Places  implements java.io.Serializable {


     private String id;
     private String url;
     private String placeType;
     private String name;
     private String fullName;
     private String countryCode;
     private String country;
     private Serializable PBoundingBox;
     private Set tweets = new HashSet(0);

    public Places() {
    }

	
    public Places(String id) {
        this.id = id;
    }
    public Places(String id, String url, String placeType, String name, String fullName, String countryCode, String country, Serializable PBoundingBox, Set tweets) {
       this.id = id;
       this.url = url;
       this.placeType = placeType;
       this.name = name;
       this.fullName = fullName;
       this.countryCode = countryCode;
       this.country = country;
       this.PBoundingBox = PBoundingBox;
       this.tweets = tweets;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getPlaceType() {
        return this.placeType;
    }
    
    public void setPlaceType(String placeType) {
        this.placeType = placeType;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    public String getCountryCode() {
        return this.countryCode;
    }
    
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public Serializable getPBoundingBox() {
        return this.PBoundingBox;
    }
    
    public void setPBoundingBox(Serializable PBoundingBox) {
        this.PBoundingBox = PBoundingBox;
    }
    public Set getTweets() {
        return this.tweets;
    }
    
    public void setTweets(Set tweets) {
        this.tweets = tweets;
    }




}


