package tfisher.entities;
// Generated Jun 4, 2014 12:06:28 PM by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tweet generated by hbm2java
 */
public class Tweet  implements java.io.Serializable {


     private String idStr;
     private Users users;
     private Places places;
     private String createdAt;
     private String text;
     private String source;
     private Boolean truncated;
     private String NInReplyToStatusIdStr;
     private String NInReplyToUserIdStr;
     private String NInReplyToScreenName;
     private Serializable NCoordinates;
     private Integer retweetCount;
     private Integer NFavoriteCount;
     private Boolean NFavorited;
     private String filterLevel;
     private String NLang;
     private Boolean PRetweeted;
     private String PCurrentUserRetweet;
     private Date time;
     private Set hashtagses = new HashSet(0);
     private Set urls = new HashSet(0);
     private Set medias = new HashSet(0);

    public Tweet() {
    }

	
    public Tweet(String idStr) {
        this.idStr = idStr;
    }
    public Tweet(String idStr, Users users, Places places, String createdAt, String text, String source, Boolean truncated, String NInReplyToStatusIdStr, String NInReplyToUserIdStr, String NInReplyToScreenName, Serializable NCoordinates, Integer retweetCount, Integer NFavoriteCount, Boolean NFavorited, String filterLevel, String NLang, Boolean PRetweeted, String PCurrentUserRetweet, Date time, Set hashtagses, Set urls, Set medias) {
       this.idStr = idStr;
       this.users = users;
       this.places = places;
       this.createdAt = createdAt;
       this.text = text;
       this.source = source;
       this.truncated = truncated;
       this.NInReplyToStatusIdStr = NInReplyToStatusIdStr;
       this.NInReplyToUserIdStr = NInReplyToUserIdStr;
       this.NInReplyToScreenName = NInReplyToScreenName;
       this.NCoordinates = NCoordinates;
       this.retweetCount = retweetCount;
       this.NFavoriteCount = NFavoriteCount;
       this.NFavorited = NFavorited;
       this.filterLevel = filterLevel;
       this.NLang = NLang;
       this.PRetweeted = PRetweeted;
       this.PCurrentUserRetweet = PCurrentUserRetweet;
       this.time = time;
       this.hashtagses = hashtagses;
       this.urls = urls;
       this.medias = medias;
    }
   
    public String getIdStr() {
        return this.idStr;
    }
    
    public void setIdStr(String idStr) {
        this.idStr = idStr;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Places getPlaces() {
        return this.places;
    }
    
    public void setPlaces(Places places) {
        this.places = places;
    }
    public String getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }
    public Boolean getTruncated() {
        return this.truncated;
    }
    
    public void setTruncated(Boolean truncated) {
        this.truncated = truncated;
    }
    public String getNInReplyToStatusIdStr() {
        return this.NInReplyToStatusIdStr;
    }
    
    public void setNInReplyToStatusIdStr(String NInReplyToStatusIdStr) {
        this.NInReplyToStatusIdStr = NInReplyToStatusIdStr;
    }
    public String getNInReplyToUserIdStr() {
        return this.NInReplyToUserIdStr;
    }
    
    public void setNInReplyToUserIdStr(String NInReplyToUserIdStr) {
        this.NInReplyToUserIdStr = NInReplyToUserIdStr;
    }
    public String getNInReplyToScreenName() {
        return this.NInReplyToScreenName;
    }
    
    public void setNInReplyToScreenName(String NInReplyToScreenName) {
        this.NInReplyToScreenName = NInReplyToScreenName;
    }
    public Serializable getNCoordinates() {
        return this.NCoordinates;
    }
    
    public void setNCoordinates(Serializable NCoordinates) {
        this.NCoordinates = NCoordinates;
    }
    public Integer getRetweetCount() {
        return this.retweetCount;
    }
    
    public void setRetweetCount(Integer retweetCount) {
        this.retweetCount = retweetCount;
    }
    public Integer getNFavoriteCount() {
        return this.NFavoriteCount;
    }
    
    public void setNFavoriteCount(Integer NFavoriteCount) {
        this.NFavoriteCount = NFavoriteCount;
    }
    public Boolean getNFavorited() {
        return this.NFavorited;
    }
    
    public void setNFavorited(Boolean NFavorited) {
        this.NFavorited = NFavorited;
    }
    public String getFilterLevel() {
        return this.filterLevel;
    }
    
    public void setFilterLevel(String filterLevel) {
        this.filterLevel = filterLevel;
    }
    public String getNLang() {
        return this.NLang;
    }
    
    public void setNLang(String NLang) {
        this.NLang = NLang;
    }
    public Boolean getPRetweeted() {
        return this.PRetweeted;
    }
    
    public void setPRetweeted(Boolean PRetweeted) {
        this.PRetweeted = PRetweeted;
    }
    public String getPCurrentUserRetweet() {
        return this.PCurrentUserRetweet;
    }
    
    public void setPCurrentUserRetweet(String PCurrentUserRetweet) {
        this.PCurrentUserRetweet = PCurrentUserRetweet;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }
    public Set getHashtagses() {
        return this.hashtagses;
    }
    
    public void setHashtagses(Set hashtagses) {
        this.hashtagses = hashtagses;
    }
    public Set getUrls() {
        return this.urls;
    }
    
    public void setUrls(Set urls) {
        this.urls = urls;
    }
    public Set getMedias() {
        return this.medias;
    }
    
    public void setMedias(Set medias) {
        this.medias = medias;
    }




}


