package tfisher.entities;
// Generated Jun 4, 2014 12:06:28 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private String id;
     private String name;
     private String screenName;
     private String NLocation;
     private String NUrl;
     private String NDescription;
     private Boolean protected_;
     private Integer followersCount;
     private Integer friendsCount;
     private Integer listedCount;
     private String createdAt;
     private Integer favouritesCount;
     private Integer NUtcOffset;
     private Boolean geoEnabled;
     private Boolean verified;
     private Integer statusesCount;
     private String lang;
     private Boolean contributorsEnabled;
     private Boolean isTranslator;
     private String profileBackgroundColor;
     private String profileBackgroundImageUrl;
     private String profileBackgroundImageUrlHttps;
     private Boolean profileBackgroundTile;
     private String profileImageUrl;
     private String profileImageUrlHttps;
     private String profileBannerUrl;
     private String profileLinkColor;
     private String profileSidebarBorderColor;
     private String profileSidebarFillColor;
     private String profileTextColor;
     private Boolean profileUseBackgroundImage;
     private Boolean defaultProfile;
     private Boolean defaultProfileImage;
     private Boolean NFollowRequestSent;
     private String NNotifications;
     private String NTimeZone;
     private Set tweets = new HashSet(0);

    public Users() {
    }

	
    public Users(String id) {
        this.id = id;
    }
    public Users(String id, String name, String screenName, String NLocation, String NUrl, String NDescription, Boolean protected_, Integer followersCount, Integer friendsCount, Integer listedCount, String createdAt, Integer favouritesCount, Integer NUtcOffset, Boolean geoEnabled, Boolean verified, Integer statusesCount, String lang, Boolean contributorsEnabled, Boolean isTranslator, String profileBackgroundColor, String profileBackgroundImageUrl, String profileBackgroundImageUrlHttps, Boolean profileBackgroundTile, String profileImageUrl, String profileImageUrlHttps, String profileBannerUrl, String profileLinkColor, String profileSidebarBorderColor, String profileSidebarFillColor, String profileTextColor, Boolean profileUseBackgroundImage, Boolean defaultProfile, Boolean defaultProfileImage, Boolean NFollowRequestSent, String NNotifications, String NTimeZone, Set tweets) {
       this.id = id;
       this.name = name;
       this.screenName = screenName;
       this.NLocation = NLocation;
       this.NUrl = NUrl;
       this.NDescription = NDescription;
       this.protected_ = protected_;
       this.followersCount = followersCount;
       this.friendsCount = friendsCount;
       this.listedCount = listedCount;
       this.createdAt = createdAt;
       this.favouritesCount = favouritesCount;
       this.NUtcOffset = NUtcOffset;
       this.geoEnabled = geoEnabled;
       this.verified = verified;
       this.statusesCount = statusesCount;
       this.lang = lang;
       this.contributorsEnabled = contributorsEnabled;
       this.isTranslator = isTranslator;
       this.profileBackgroundColor = profileBackgroundColor;
       this.profileBackgroundImageUrl = profileBackgroundImageUrl;
       this.profileBackgroundImageUrlHttps = profileBackgroundImageUrlHttps;
       this.profileBackgroundTile = profileBackgroundTile;
       this.profileImageUrl = profileImageUrl;
       this.profileImageUrlHttps = profileImageUrlHttps;
       this.profileBannerUrl = profileBannerUrl;
       this.profileLinkColor = profileLinkColor;
       this.profileSidebarBorderColor = profileSidebarBorderColor;
       this.profileSidebarFillColor = profileSidebarFillColor;
       this.profileTextColor = profileTextColor;
       this.profileUseBackgroundImage = profileUseBackgroundImage;
       this.defaultProfile = defaultProfile;
       this.defaultProfileImage = defaultProfileImage;
       this.NFollowRequestSent = NFollowRequestSent;
       this.NNotifications = NNotifications;
       this.NTimeZone = NTimeZone;
       this.tweets = tweets;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getScreenName() {
        return this.screenName;
    }
    
    public void setScreenName(String screenName) {
        this.screenName = screenName;
    }
    public String getNLocation() {
        return this.NLocation;
    }
    
    public void setNLocation(String NLocation) {
        this.NLocation = NLocation;
    }
    public String getNUrl() {
        return this.NUrl;
    }
    
    public void setNUrl(String NUrl) {
        this.NUrl = NUrl;
    }
    public String getNDescription() {
        return this.NDescription;
    }
    
    public void setNDescription(String NDescription) {
        this.NDescription = NDescription;
    }
    public Boolean getProtected_() {
        return this.protected_;
    }
    
    public void setProtected_(Boolean protected_) {
        this.protected_ = protected_;
    }
    public Integer getFollowersCount() {
        return this.followersCount;
    }
    
    public void setFollowersCount(Integer followersCount) {
        this.followersCount = followersCount;
    }
    public Integer getFriendsCount() {
        return this.friendsCount;
    }
    
    public void setFriendsCount(Integer friendsCount) {
        this.friendsCount = friendsCount;
    }
    public Integer getListedCount() {
        return this.listedCount;
    }
    
    public void setListedCount(Integer listedCount) {
        this.listedCount = listedCount;
    }
    public String getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }
    public Integer getFavouritesCount() {
        return this.favouritesCount;
    }
    
    public void setFavouritesCount(Integer favouritesCount) {
        this.favouritesCount = favouritesCount;
    }
    public Integer getNUtcOffset() {
        return this.NUtcOffset;
    }
    
    public void setNUtcOffset(Integer NUtcOffset) {
        this.NUtcOffset = NUtcOffset;
    }
    public Boolean getGeoEnabled() {
        return this.geoEnabled;
    }
    
    public void setGeoEnabled(Boolean geoEnabled) {
        this.geoEnabled = geoEnabled;
    }
    public Boolean getVerified() {
        return this.verified;
    }
    
    public void setVerified(Boolean verified) {
        this.verified = verified;
    }
    public Integer getStatusesCount() {
        return this.statusesCount;
    }
    
    public void setStatusesCount(Integer statusesCount) {
        this.statusesCount = statusesCount;
    }
    public String getLang() {
        return this.lang;
    }
    
    public void setLang(String lang) {
        this.lang = lang;
    }
    public Boolean getContributorsEnabled() {
        return this.contributorsEnabled;
    }
    
    public void setContributorsEnabled(Boolean contributorsEnabled) {
        this.contributorsEnabled = contributorsEnabled;
    }
    public Boolean getIsTranslator() {
        return this.isTranslator;
    }
    
    public void setIsTranslator(Boolean isTranslator) {
        this.isTranslator = isTranslator;
    }
    public String getProfileBackgroundColor() {
        return this.profileBackgroundColor;
    }
    
    public void setProfileBackgroundColor(String profileBackgroundColor) {
        this.profileBackgroundColor = profileBackgroundColor;
    }
    public String getProfileBackgroundImageUrl() {
        return this.profileBackgroundImageUrl;
    }
    
    public void setProfileBackgroundImageUrl(String profileBackgroundImageUrl) {
        this.profileBackgroundImageUrl = profileBackgroundImageUrl;
    }
    public String getProfileBackgroundImageUrlHttps() {
        return this.profileBackgroundImageUrlHttps;
    }
    
    public void setProfileBackgroundImageUrlHttps(String profileBackgroundImageUrlHttps) {
        this.profileBackgroundImageUrlHttps = profileBackgroundImageUrlHttps;
    }
    public Boolean getProfileBackgroundTile() {
        return this.profileBackgroundTile;
    }
    
    public void setProfileBackgroundTile(Boolean profileBackgroundTile) {
        this.profileBackgroundTile = profileBackgroundTile;
    }
    public String getProfileImageUrl() {
        return this.profileImageUrl;
    }
    
    public void setProfileImageUrl(String profileImageUrl) {
        this.profileImageUrl = profileImageUrl;
    }
    public String getProfileImageUrlHttps() {
        return this.profileImageUrlHttps;
    }
    
    public void setProfileImageUrlHttps(String profileImageUrlHttps) {
        this.profileImageUrlHttps = profileImageUrlHttps;
    }
    public String getProfileBannerUrl() {
        return this.profileBannerUrl;
    }
    
    public void setProfileBannerUrl(String profileBannerUrl) {
        this.profileBannerUrl = profileBannerUrl;
    }
    public String getProfileLinkColor() {
        return this.profileLinkColor;
    }
    
    public void setProfileLinkColor(String profileLinkColor) {
        this.profileLinkColor = profileLinkColor;
    }
    public String getProfileSidebarBorderColor() {
        return this.profileSidebarBorderColor;
    }
    
    public void setProfileSidebarBorderColor(String profileSidebarBorderColor) {
        this.profileSidebarBorderColor = profileSidebarBorderColor;
    }
    public String getProfileSidebarFillColor() {
        return this.profileSidebarFillColor;
    }
    
    public void setProfileSidebarFillColor(String profileSidebarFillColor) {
        this.profileSidebarFillColor = profileSidebarFillColor;
    }
    public String getProfileTextColor() {
        return this.profileTextColor;
    }
    
    public void setProfileTextColor(String profileTextColor) {
        this.profileTextColor = profileTextColor;
    }
    public Boolean getProfileUseBackgroundImage() {
        return this.profileUseBackgroundImage;
    }
    
    public void setProfileUseBackgroundImage(Boolean profileUseBackgroundImage) {
        this.profileUseBackgroundImage = profileUseBackgroundImage;
    }
    public Boolean getDefaultProfile() {
        return this.defaultProfile;
    }
    
    public void setDefaultProfile(Boolean defaultProfile) {
        this.defaultProfile = defaultProfile;
    }
    public Boolean getDefaultProfileImage() {
        return this.defaultProfileImage;
    }
    
    public void setDefaultProfileImage(Boolean defaultProfileImage) {
        this.defaultProfileImage = defaultProfileImage;
    }
    public Boolean getNFollowRequestSent() {
        return this.NFollowRequestSent;
    }
    
    public void setNFollowRequestSent(Boolean NFollowRequestSent) {
        this.NFollowRequestSent = NFollowRequestSent;
    }
    public String getNNotifications() {
        return this.NNotifications;
    }
    
    public void setNNotifications(String NNotifications) {
        this.NNotifications = NNotifications;
    }
    public String getNTimeZone() {
        return this.NTimeZone;
    }
    
    public void setNTimeZone(String NTimeZone) {
        this.NTimeZone = NTimeZone;
    }
    public Set getTweets() {
        return this.tweets;
    }
    
    public void setTweets(Set tweets) {
        this.tweets = tweets;
    }




}


